#!/usr/bin/env bash

set -e

cd "${BASH_SOURCE%/*}"

heuristic="$1"
shift
for input_file in input/*; do
    echo "$input_file"
    ./main.py "$input_file" "$heuristic" "$@" &
done

wait
echo "Finished $heuristic"
